# LAB TASK'S

# Task 01

### In this task simply multiplication is done by using constants

In [1]:
import pandas as pd
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
# Define a TensorFlow constant tensor
tensor = tf.constant([[1, 2], [3, 4]])

# Define a scalar value
scalar = 4

# Multiply the tensor by the scalar value
result = tensor * scalar

# Print the result
print("Original Tensor:")
print(tensor)
print("\nScalar Value:")
print(scalar)
print("\nResult after multiplication:")
print(result)


Original Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Scalar Value:
4

Result after multiplication:
tf.Tensor(
[[ 4  8]
 [12 16]], shape=(2, 2), dtype=int32)


# Task 02

### In this task dot product is being calculated by using 2 vectors

In [4]:
import tensorflow as tf

# Define two 1-D tensors (vectors)
vector1 = tf.constant([1, 2, 3])
vector2 = tf.constant([4, 5, 6])

# Compute the dot product of the two vectors
dot_product = tf.tensordot(vector1, vector2, axes=1)

# Print the dot product
print("Dot Product:", dot_product.numpy())


Dot Product: 32


# Task 03

### In this task simply arithmetic operations are performed

In [5]:
import tensorflow as tf

# Define the matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Addition
addition_result = tf.add(matrix1, matrix2)

# Subtraction
subtraction_result = tf.subtract(matrix1, matrix2)

# Element-wise multiplication
element_wise_multiplication_result = tf.multiply(matrix1, matrix2)

# Print the results
print("Matrix1:")
print(matrix1.numpy())
print("\nMatrix2:")
print(matrix2.numpy())
print("\nAddition Result:")
print(addition_result.numpy())
print("\nSubtraction Result:")
print(subtraction_result.numpy())
print("\nElement-wise Multiplication Result:")
print(element_wise_multiplication_result.numpy())


Matrix1:
[[1 2]
 [3 4]]

Matrix2:
[[5 6]
 [7 8]]

Addition Result:
[[ 6  8]
 [10 12]]

Subtraction Result:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication Result:
[[ 5 12]
 [21 32]]


# EXERCISE

### 1) Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [6]:
import tensorflow as tf

In [7]:
vector = tf.constant([1, 2, 3, 4, 5])
scalar = tf.constant(2)
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

### 2)Find the shape, rank and size of the tensors you created in 1.

In [8]:
vector_shape = tf.shape(vector)
vector_rank = tf.rank(vector)
vector_size = tf.size(vector)

scalar_shape = tf.shape(scalar)
scalar_rank = tf.rank(scalar)
scalar_size = tf.size(scalar)

matrix_shape = tf.shape(matrix)
matrix_rank = tf.rank(matrix)
matrix_size = tf.size(matrix)

tensor_shape = tf.shape(tensor)
tensor_rank = tf.rank(tensor)
tensor_size = tf.size(tensor)

In [10]:
# Print the results
print("Vector Shape:", vector_shape.numpy())
print("Vector Rank:", vector_rank.numpy())
print("Vector Size:", vector_size.numpy())

print("\nScalar Shape:", scalar_shape.numpy())
print("Scalar Rank:", scalar_rank.numpy())
print("Scalar Size:", scalar_size.numpy())

print("\nMatrix Shape:", matrix_shape.numpy())
print("Matrix Rank:", matrix_rank.numpy())
print("Matrix Size:", matrix_size.numpy())

print("\nTensor Shape:", tensor_shape.numpy())
print("Tensor Rank:", tensor_rank.numpy())
print("Tensor Size:", tensor_size.numpy())

Vector Shape: [5]
Vector Rank: 1
Vector Size: 5

Scalar Shape: []
Scalar Rank: 0
Scalar Size: 1

Matrix Shape: [2 2]
Matrix Rank: 2
Matrix Size: 4

Tensor Shape: [2 2 2]
Tensor Rank: 3
Tensor Size: 8


### 3)Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [11]:
random_tensor1 = tf.random.uniform(shape=[5, 300])
random_tensor2 = tf.random.uniform(shape=[5, 300])

### 4)Multiply the two tensors you created in 3 using matrix multiplication.

In [12]:
matrix_multiplication_result = tf.matmul(random_tensor1, random_tensor2, transpose_b=True)

In [13]:
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result.numpy())


Matrix Multiplication Result:
[[77.891235 78.69267  81.48962  75.18346  69.47348 ]
 [77.719574 78.02087  80.31923  75.26994  72.222336]
 [76.78998  76.085754 74.83748  74.46388  69.49411 ]
 [84.762085 84.46376  84.567    82.41521  76.9682  ]
 [77.02532  78.45811  76.17929  74.35171  71.33738 ]]


### 5)Multiply the two tensors you created in 3 using dot product.

In [14]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
random_tensor1 = tf.random.uniform(shape=[5, 300])
random_tensor2 = tf.random.uniform(shape=[5, 300])

# Reshape one of the tensors for dot product (matrix multiplication)
reshaped_tensor1 = tf.reshape(random_tensor1, shape=[300, 5])

# Perform dot product (matrix multiplication)
dot_product_result = tf.matmul(reshaped_tensor1, random_tensor2)

In [15]:
# Print the result
print("Dot Product Result:")
print(dot_product_result.numpy())

Dot Product Result:
[[1.6897093  1.1788983  0.78074425 ... 1.3425853  1.9414192  1.342517  ]
 [2.0850508  1.3793294  0.939673   ... 1.7934079  2.6091418  1.951101  ]
 [1.6882111  0.9954923  0.7238284  ... 1.2494614  1.7951597  1.3817602 ]
 ...
 [1.1337118  0.70035076 0.50315773 ... 0.8011534  1.3715148  1.1171256 ]
 [1.1009252  0.7015171  0.478652   ... 1.0157886  1.4758507  1.149231  ]
 [1.5652648  0.77283716 0.5053524  ... 1.2661881  1.6604576  1.3114713 ]]


### 6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [16]:
random_tensor_3d = tf.random.uniform(shape=[224, 224, 3])

### 7) Find the min and max values of the tensor you created in 6.

In [17]:
min_value = tf.reduce_min(random_tensor_3d)
max_value = tf.reduce_max(random_tensor_3d)

In [18]:
print("\nMin Value:", min_value.numpy())
print("Max Value:", max_value.numpy())


Min Value: 2.503395e-06
Max Value: 0.999992


### 8)Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [19]:
random_tensor_4d = tf.random.uniform(shape=[1, 224, 224, 3])
squeezed_tensor = tf.squeeze(random_tensor_4d, axis=0)

In [20]:
print("\nSqueezed Tensor Shape:", tf.shape(squeezed_tensor).numpy())


Squeezed Tensor Shape: [224 224   3]


### 9) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [21]:
tensor_max_index = tf.argmax(tf.constant([5, 3, 8, 2, 7, 4, 9, 1, 6, 0]))

In [22]:
print("Max Index in Tensor:", tensor_max_index.numpy())

Max Index in Tensor: 6
